name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoyoinc/profile-3d-contrib@main
        with:
          username: Shushant-k1
          output: ./profile-3d-contrib/profile-night-view.svg
      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./profile-3d-contrib/profile-night-view.svg
          git commit -m "Update 3d contribution calendar"
          git push
